# Generated by Django 4.2 on 2023-05-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0018_alter_papers_filename_notes'),
        ('institues', '0002_alter_college_college_logo_alter_college_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.university', unique=True),
        ),
    ]
