# Generated by Django 4.2 on 2023-05-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institues', '0005_alter_college_college_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_logo',
            field=models.FileField(upload_to='static/institutes/logos/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
